In [1]:
import numpy as np

In [2]:
num_paes = 1000

In [3]:
# Inventando paezinhos imaginários.

# Pesos: cerca de 50g, com desvio padrão de 3g.
pesos = 50 + 3*np.random.randn(num_paes, 1)

# Temperatura: cerca de 22 graus Celsius, com desvio padrão de 5 graus.
temps = 22 + 5*np.random.randn(num_paes, 1)

# Volume em ml: 3 ml por grama de massa, mais 4ml por grau acima de 22.
volume = 3*pesos + 4*(temps - 22) + 5*np.random.randn(num_paes, 1)

In [4]:
X = np.c_[pesos, temps]
y = volume

In [5]:
X.shape, y.shape

((1000, 2), (1000, 1))

In [6]:
# Vamos dividir em treino e teste.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [7]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

# Aqui é onde o modelo aprende.
model.fit(X_train, y_train)

LinearRegression()

In [8]:
model.intercept_, model.coef_

(array([-85.34979922]), array([[2.95561353, 3.98566281]]))

O modelo final é:

$$
\hat{y} = \overset{\theta_0}{-81.65} + \overset{\theta_1}{2.88} x_1 + \overset{\theta_2}{4.02} x_2
$$

In [9]:
y_pred = model.predict(X_test)

In [10]:
from sklearn.metrics import root_mean_squared_error

root_mean_squared_error(y_test, y_pred)

np.float64(5.109938366270234)

Agora suponha que o padeiro ficou louco, e resolveu duplicar a coluna de peso de pãozinho:

In [11]:
X = np.c_[pesos, pesos, temps]
y = volume

In [12]:
X[:5,:]

array([[49.73843175, 49.73843175, 20.75481672],
       [46.72451603, 46.72451603, 13.74788559],
       [49.08646389, 49.08646389, 25.3184392 ],
       [51.86895371, 51.86895371, 20.30310365],
       [53.03037924, 53.03037924, 19.6183955 ]])

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [14]:
model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

In [15]:
np.linalg.inv(X_train.T @ X_train) @ X_train.T @ y_train

array([[ 2.75249141],
       [-0.09416334],
       [ 3.7546734 ]])

In [16]:
from sklearn.linear_model import Ridge

model = Ridge(alpha=1)

model.fit(X_train, y_train)

Ridge(alpha=1)

In [17]:
model.coef_, model.intercept_

(array([[1.47154405, 1.47154405, 4.01450505]]), array([-85.31848313]))